# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'Getting started'

env:
  #GEMINI_API_KEY: AIzaSyBuyz_c5oSLp27hH2_DCxq-OZ1ZKIW-v0Q

providers:
  - "google:gemini-2.5-flash-lite"
  - "google:gemini-2.5-flash"
    

tests: file://tests/casos.yaml