# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'Getting started'

env:
  GEMINI_API_KEY: AIzaSyAC-vGbZXC5EHjTgO0d8f5VWh2t0WJ35VU

providers:
  - id: google:gemini-2.5-pro
    config:
      apiKey: AIzaSyAC-vGbZXC5EHjTgO0d8f5VWh2t0WJ35VU

tests: file://tests/casos.yaml